# This is a basic workflow to help you get started with Actions
name: Push commit
on: 
  workflow_dispatch: #manual trigger
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: sed -i -e "s~\(<Version>[0-9]*\.[0-9]*\.[0-9]*</Version>\)~<Version>11.22.33</Version>~" ./report.txt
      - name: Commit report
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add report.txt
          git commit -m "Automated update"
          git push
