# This is a basic workflow to help you get started with Actions

name: outputs
env:
  MY_VAR: ''
# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: Increment version
        run: echo "MY_VAR=$( echo NIKOLA)">>$GITHUB_ENV
    
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::${{ env.MY_VAR }}"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
