# This is a basic workflow to help you get started with Actions

name: read tag

on:
  workflow_dispatch: #manual trigger

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  read:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Git
        run: |
             git config --global user.name nikola-copsfs
             git config --global user.email nikola-copsfs@users.noreply.github.com
             git fetch --tags
             
      - name: Print tag
        run: echo $(git describe --tags --always --abbrev=0)
             
